version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI